/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oss.pages;

import com.nordea.pubsubapi.Publisher;
import com.oss.Page;
import java.awt.Color;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author g46737
 */
public class ChatSender extends javax.swing.JPanel {
    

    Publisher pub;
    
    public ChatSender(Page page) {
        pub =  Publisher.getInstance();
        initComponents();
        DefaultCaret caret = (DefaultCaret)jTextArea1.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(3, 1));

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jTextField1.setText("Enter Topic Name here");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);

        add(jPanel1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Write you text here!");
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2);
    }// </editor-fold>//GEN-END:initComponents

    private volatile boolean execute;

    public void startExecuting() {
        this.execute = true;
        thread.start();
        jButton1.setBackground(Color.RED);
    }

    public void stopExecuting() {
        this.execute = false;
        jButton1.setBackground(Color.GRAY);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (!execute) {
            startExecuting();

        } else {
            stopExecuting();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    Random rn = new Random();
    int i = 0;
    Thread thread = new Thread() {
        @Override
        public void run() {
            while (execute) {
                i++;
                try {
                    Thread.sleep(100);
                    //final int nextInt = rn.nextInt(10000);
                    pub.send(Publisher.default_topic, i+"");
                    jTextArea1.append(Publisher.default_topic + " : " + i + "\n");
                    jTextArea1.repaint();
                } catch (InterruptedException ex) {
                    Logger.getLogger(ChatSender.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    };
}
