/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.oss.pages;

import com.nordea.pubsubapi.Connector;
import com.nordea.pubsubapi.Subscriber;
import com.oss.Page;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
//import com.nordea.pubsubmicroservice.

/**
 *
 * @author g46737
 */
public class RxReciever extends javax.swing.JPanel {

    /**
     * Creates new form RxReciever
     */
    public RxReciever(Page page) {
        initComponents();
    }
    
    private volatile boolean running = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("Receive");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

  

        
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        running = !running;
        
        Thread t = new Thread()
        {
            @Override
            public void run()
            {
                Subscriber sub = new Subscriber();
                while(running)
                {
                    final ArrayList<String> messages = sub.getMessages(Subscriber.default_topic);
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(RxReciever.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (String message : messages)
                    {
                        System.out.println(message);
                        jTextArea1.append(message);
                    }
                    sub.getMessages(Connector.default_topic);
                }
            }
        };
        t.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
