/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oss.pages;

import com.oss.Page;
import java.awt.Color;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author g46737
 */
public class RxSender extends javax.swing.JPanel {

    public RxSender(Page page) {
        initComponents();
        DefaultCaret caret = (DefaultCaret)jTextArea1.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private volatile boolean execute;

    public void startExecuting() {
        this.execute = true;
        thread.start();
        jButton1.setBackground(Color.RED);
    }

    public void stopExecuting() {
        this.execute = false;
        jButton1.setBackground(Color.GRAY);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (!execute) {
            startExecuting();

        } else {
            stopExecuting();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    Random rn = new Random();
    int i = 0;
    Thread thread = new Thread() {
        @Override
        public void run() {
            while (execute) {
                i++;
                try {
                    Thread.sleep(100);
                    final int nextInt = rn.nextInt(10000);
                    jTextArea1.append(i + " : " + nextInt + "\n");
                    jTextArea1.repaint();
                } catch (InterruptedException ex) {
                    Logger.getLogger(RxSender.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    };
}
