/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oss.components;

import com.jtable.generic.DynamicTableModel;
import com.jtable.generic.ExampleDataClass;
import java.util.ArrayList;

/**
 *
 * @author g46737
 */
public class TablePanel extends javax.swing.JPanel {
    ArrayList<Object> dataList1 = new ArrayList();
    ExampleDataClass c1 = new ExampleDataClass("This", "Is");
    ExampleDataClass c2 = new ExampleDataClass("Real", "Test");
    ExampleDataClass c3 = new ExampleDataClass("Of a", "Dynamic JTable");
    
    /**
     * Creates new form tablePanel
     */
    public TablePanel() {
        dataList1.add(c1);
        dataList1.add(c2);
        dataList1.add(c3);
        initComponents();
    }
      
    DynamicTableModel dynamicTableModel = new DynamicTableModel();
     class TablePanelModel extends DynamicTableModel
     {
        public TablePanelModel() {
            setModel(dataList1, ExampleDataClass.class);  
        }                          
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new TablePanelModel());
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
